apiVersion: v1
kind: Service
metadata:
  name: {{ include "sb-nginx.fullname" . }}
  labels: {{- include "sb-nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "sb-nginx.selectorLabels" . | nindent 4 }}
