apiVersion: v1
data:
  password: cGFzc3dvcmQxMjM= #password123
  username: YWRtaW51c2Vy #adminuser
kind: Secret
metadata:
  annotations:
    "environment": "demo"
    "app": "mongo"
  name: mongo-creds
